#!/bin/sh /etc/rc.common

# These variables are consumed by OpenWrt's rc.common framework.
# shellcheck disable=SC2034
USE_PROCD=1
# shellcheck disable=SC2034
START=95
# shellcheck disable=SC2034
STOP=10

PROG=/usr/bin/meowdeck
CONFIG=/etc/meowdeck/config.json

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -config "$CONFIG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param limits nofile="4096 4096"
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger meowdeck
}
